name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          # note: https://www.azul.com/products/core/openjdk-terms-of-use/
          distribution: 'zulu'
          cache: maven

      - name: Build with Maven
        # enable parallel build
        run: mvn -T 4 -B package --file pom.xml
