name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-24.04

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          # note: https://www.azul.com/products/core/openjdk-terms-of-use/
          distribution: 'zulu'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
